FROM eclipse-temurin:17-jre-alpine
# Install curl jq
#RUN apk add curl jq
# workspace
WORKDIR /home/selenium-docker
# Add the required files
ADD target/docker-resources     ./
#Entrypoint
ENTRYPOINT ["sh","-c","java -cp 'libs/*:.' \
-Dselenium.grid.enabled=true \
-Dselenium.grid.hubHost=${HUB_HOST} \
-Dbrowser=${BROWSER} \
org.testng.TestNG \
-threadcount ${THREAD_COUNT} \
test-suites/${TEST_SUITE}"]